// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StopWatchSync(arg1) {
  return window['go']['main']['App']['StopWatchSync'](arg1);
}

export function WatchSync(arg1) {
  return window['go']['main']['App']['WatchSync'](arg1);
}
