// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DownloadAndInstall(arg1) {
  return window['go']['main']['App']['DownloadAndInstall'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StopWatchMoveLibrary() {
  return window['go']['main']['App']['StopWatchMoveLibrary']();
}

export function StopWatchSync(arg1) {
  return window['go']['main']['App']['StopWatchSync'](arg1);
}

export function WatchMoveLibrary() {
  return window['go']['main']['App']['WatchMoveLibrary']();
}

export function WatchSync(arg1) {
  return window['go']['main']['App']['WatchSync'](arg1);
}
