// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory():Promise<string>;

export function StopWatchSync(arg1:number):Promise<void>;

export function WatchSync(arg1:number):Promise<void>;
