// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate():Promise<{available:boolean,version:string,notes:string}>;

export function DownloadAndInstall(arg1:string):Promise<void>;

export function GetVersion():Promise<string>;

export function SelectDirectory():Promise<string>;

export function StopWatchMoveLibrary():Promise<void>;

export function StopWatchSync(arg1:number):Promise<void>;

export function WatchMoveLibrary():Promise<void>;

export function WatchSync(arg1:number):Promise<void>;
